[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
# startCommand is defined in Dockerfile CMD
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
