[theme]
primaryColor = "#575757"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#D9D9D9"
textColor = "#323232"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
